owner: macbrayne
repo: status

sites:
  - name: Nextcloud
    url: https://nextcloud.macbrayne.de/login?$SECRET
    icon: https://apps.nextcloud.com/static/assets/img/logo-icon.svg
  - name: Editor
    url: https://$EDITOR?$SECRET
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Visual_Studio_Code_1.35_icon.svg/240px-Visual_Studio_Code_1.35_icon.svg.png
  - name: Reverse Proxy
    url: https://proxy.macbrayne.de?$SECRET
    icon: https://raw.githubusercontent.com/jlesage/docker-templates/master/jlesage/images/nginx-proxy-manager-icon.png
  - name: Image Hosting
    url: https://i.macbrayne.de$URL?$SECRET
    icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/xbackbone-logo.png
  - name: FRACTAVA Website
    url: https://fractava.com
    icon: https://raw.githubusercontent.com/fractava/resources/master/Logos/Symbol/gro%C3%9F/transparenter%20Hintergrund/Farbe%20weiß.png
  - name: Minecraft Server
    check: "tcp-ping"
    url: $SERVER_URL
    port: $SERVER_PORT

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: macbrayne.de
  # baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: macbrayne status
  theme: night
  introTitle: "macbrayne services status"
  introMessage:
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

user-agent: macbrayne

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
