owner: macbrayne
repo: status

sites:
  - name: Nextcloud
    url: https://nextcloud.macbrayne.de?$SECRET
    icon: https://nextcloud.com/wp-content/themes/next/assets/img/logo/logo_nextcloud_white.svg?x53054
  - name: Reverse Proxy
    url: https://proxy.macbrayne.de?$SECRET
  - name: FRACTAVA Website
    url: https://fractava.com
    icon: https://raw.githubusercontent.com/fractava/resources/master/Logos/Symbol/gro%C3%9F/transparenter%20Hintergrund/Farbe%20weiß.png
  - name: Minecraft Server
    check: "tcp-ping"
    url: $SERVER_URL
    port: $SERVER_PORT

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: macbrayne status
  introTitle: "macbrayne services Status"
  introMessage:
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
